""" Banco de dados:
    -   SQL (LINGUAGEM DE CONSULTA ESTRUTURADA)
    -   EXEMPLO
    -   SELECT * FROM CLIENTE;
    -   IRÁ CONSULTAR O BD NA TABELA DE CLIENTES.

    -   SGDB:
        -   GERENCIAR PERMISSÕES DE ACESSO
        -   ADMINISTRADOR DE BANCO DE DADOS (DBA)
        -   CRIAR CONSULTAS PERSONALIZADAS
        -   SELECT * FROM CLIENTES;

    -   ORM: MAPEAMENTO OBJETO RELACIONAL
        -   USAR A LINGUAGEM DE PROGRAMAÇAO PARA MANIPULAR O BANCO DE DADOS

    - INSTALANDO ORM PARA PYTHON:
        - pip install sqlalchemy 

"""